module.exports = {
  docs: {
    'Overview': [
      'installation',
      'defining-entities',
      'relationships',
      'entity-manager',
      'repositories',
    ],
    'Fundamentals': [
      'identity-map',
      'entity-references',
      'entity-constructors',
      'collections',
      'unit-of-work',
      'transactions',
      'cascading',
      'deployment',
    ],
    'Advanced Features': [
      'nested-populate',
      'query-conditions',
      'query-builder',
      'serializing',
      'entity-helper',
      'property-validation',
      'lifecycle-hooks',
      'naming-strategy',
      'metadata-cache',
      'debugging',
      'schema-generator',
      'entity-generator',
      'migrations',
      'read-connections',
    ],
    'Usage with Different Drivers': [
      'usage-with-sql',
      'usage-with-mongo',
    ],
    'Recipes': [
      'usage-with-nestjs',
      'usage-with-js',
      'custom-driver',
      'multiple-schemas',
    ],
    'Example Integrations': [
      { type: 'link', label: 'Express + MongoDB + TypeScript', href: 'https://github.com/mikro-orm/mikro-orm-examples/tree/master/express-ts' },
      { type: 'link', label: 'Nest + MySQL + TypeScript', href: 'https://github.com/mikro-orm/mikro-orm-examples/tree/master/nest' },
      { type: 'link', label: 'Express + MongoDB + JavaScript', href: 'https://github.com/mikro-orm/mikro-orm-examples/tree/master/express-js' },
    ],
  },
};
